### ISSUE TITLE
Get support for G2 Vm´s to support Windows 11

### ISSUE THREAD

**Issue by schiffne** [Azure/azvmimagebuilder#17]
Currently it is not possible to use G2 VMs from the Shared image gallery, as only G1 are supported. For Windows 11 this is a requirement.

**Comment by Bad-Rog** [comment]
Is this per design or is this a Bug?  Gen2 Windows images are not supported with AIB at all

**Comment by schiffne** [comment]
its more a feature request, but there is no page where this could be written down. Based on Kofi´s feedback there will be support for it in December.

**Comment by kof-f** [comment]
Hey All, I know I haven't responded here, but we do support Gen2 images now. You can read more about it here: https://docs.microsoft.com/en-us/azure/virtual-machines/image-builder-overview#hyper-v-generation. I'll be closing this issue now.
