### ISSUE TITLE
AiB Accepts the Deployment of a GEN 2 VM and the Distribution Process Fails.

### ISSUE THREAD

**Issue by frestevao** [Azure/azvmimagebuilder#18]
Hello team!

On the public documentation, I see that the AiB does not support the GEN 2 VM.

https://docs.microsoft.com/en-us/azure/virtual-machines/image-builder-overview#hyper-v-generation

But it allows me to trigger the deployment and the process fails on the Image Distribution.

Source Image as a Gen 2 VM.

![SourceImageV2](https://user-images.githubusercontent.com/31082826/141488492-013be082-73c8-440a-913e-db85da285c99.png)

AiB template deployed with success.

![AiB Template Deployed](https://user-images.githubusercontent.com/31082826/141488628-4fd84ef7-6a66-4b96-bf6c-06ed0800014e.png)

AiB generates the Managed Image as generation 1

![image](https://user-images.githubusercontent.com/31082826/141492577-6b8ff7a4-e0a2-4d26-b5ac-65d7a62e7b6a.png)

SIG image with Unknow state

![image](https://user-images.githubusercontent.com/31082826/141491885-68cbe1a7-aa19-4b7d-961f-5ba4a0a14f33.png)

AiB error on Azure Portal:

        "provisioningState": "Succeeded",
        "lastRunStatus": {
            "startTime": "2021-11-12T15:04:52.400830569Z",
            "endTime": "2021-11-12T15:28:44.353389414Z",
            "runState": "Failed",
            "message": "Failed in distributing 1 images out of total 1: Some error happened, please check the error details."
        },

**Comment by Bad-Rog** [comment]
Thanks, very interested in this bugfix/feature

**Comment by srwindows** [comment]
Hey Guys!

The public document was updated!

![image](https://user-images.githubusercontent.com/31082826/143222810-77ffe79a-4dcb-4017-a436-73b06cb037e8.png)


I also did a test building a Generation 2 Image and it worked =D

![image](https://user-images.githubusercontent.com/31082826/143223014-e95f58fe-9f9e-40e1-962b-207e2e21b5a4.png)

**Comment by schiffne** [comment]
Did you deploy the template with e.g. some powershell files you used to customize the image further?

**Comment by srwindows** [comment]
Hello @schiffne,

My deployment runs a PowerShell script that enabled IIS and other settings on the Windows Server.

If you want, I can share the template with you.

Best regards,
Estevão

**Comment by Bad-Rog** [comment]
I will run my deployment now as well, installing MECM and AntiVirus, it does work with Gen1 images...
will let you know

**Comment by schiffne** [comment]
This would be great if you can share it here: For us it fails here, where it shows yellow, the script currently contains only EXIT 0
![image](https://user-images.githubusercontent.com/19165725/143247642-0c47d2cd-d70e-4694-99cb-fc1fe5e64b80.png)

**Comment by srwindows** [comment]
> This would be great if you can share it here: For us it fails here, where it shows yellow, the script currently contains only EXIT 0 ![image](https://user-images.githubusercontent.com/19165725/143247642-0c47d2cd-d70e-4694-99cb-fc1fe5e64b80.png)

What's the output on your customization.log file?

**Comment by schiffne** [comment]
it looks similiar to this. The VM WIN11! does not proceed it just stops and waits for the timeout in the template and than does the cleanup and deletes itself, here is a screenshot, where the VM is just waiting to execute that one single script:
![image](https://user-images.githubusercontent.com/19165725/143253348-c39fa296-7827-4376-9aab-c8a978664e6c.png)

**Comment by StevybSC** [comment]
Seeing the same issue. Same set of customization work fine with Gen1 (Win10), but any powershell customisation steps fail on a Gen2 (Win11) run.

Attempts to run the PS, but sits and waits until the timeout and then moves to cleanup.

**Comment by laughtonsm** [comment]
@StevybSC did you ever find a solution to this?  Currently seeing the same behaviour too

**Comment by laughtonsm** [comment]
So after further experimentation today, adding ```"runAsSystem": true``` to the PowerShell customiser appears to resolve this issue.  By default, if it isn't specified the value is false.  Changing this allowed my builds to continue without hanging
