### ISSUE TITLE
AWARENESS: Potential Service interruption on 2nd and 4th April between 1pm and 5pm PDT.

### ISSUE THREAD

**Issue by danielsollondon** [Azure/azvmimagebuilder#2]
Awareness
As the Image Builder team get closer to GA we need to do some essential regional upgrades on 2nd and 4th April between 1pm and 5pm PDT.

During this time, some Image Builder operations may slowdown and timeout, resulting in an 'InternalError', if you receive this, please wait a minimum of 30min and retry. Examples of operations that could slow down, Creating a template, starting a build getting build status.

We apologize for the temporary inconvenience during this time, please monitor this GitHub issue for updates.

Thanks,

**Comment by sagilson** [comment]
The maintenance work for 4/2 is scheduled to start at 1:15pm PDT. Customers may begin to experience interruptions as described in @danielsollondon's post. An update will be posted on this thread when the maintenance is completed and customers may resume with no interruptions.

**Comment by chadbarbedatto** [comment]
Would these activities potentially result in the following errors, both seen during the windows update customization:

```
[a40ca257-b788-4399-b407-0a35c6b237c8] PACKER OUT Build 'azure-arm' errored after 10 minutes 39 seconds: Windows update script exited with non-zero exit status: 267014
```

or 

```
[4a163427-cc12-42ca-9cb7-1b143e9c05a4] PACKER OUT Build 'azure-arm' errored after 21 minutes 6 seconds: Error removing temporary file $env:TEMP\winrmcp-88af310e-4063-4836-731a-d2d0ce3b6fc0.tmp: unknown error Post "https://13.90.72.180:5986/wsman": EOF
```

**Comment by feiyushi** [comment]
> Would these activities potentially result in the following errors, both seen during the windows update customization:
> 
> ```
> [a40ca257-b788-4399-b407-0a35c6b237c8] PACKER OUT Build 'azure-arm' errored after 10 minutes 39 seconds: Windows update script exited with non-zero exit status: 267014
> ```
> 
> or
> 
> ```
> [4a163427-cc12-42ca-9cb7-1b143e9c05a4] PACKER OUT Build 'azure-arm' errored after 21 minutes 6 seconds: Error removing temporary file $env:TEMP\winrmcp-88af310e-4063-4836-731a-d2d0ce3b6fc0.tmp: unknown error Post "https://13.90.72.180:5986/wsman": EOF
> ```

No. Your error is not related to what's happening in EU regions now.

**Comment by sagilson** [comment]
Update: There has been a delay in the maintenance work for the two EU clusters, and thus customer errors may continue past 5pm. Another update will be posted here in 2-3 hours.

**Comment by sagilson** [comment]
Update: The delay in the maintenance work for the two EU regions is still ongoing, and thus customer errors may continue past 6:30pm. Another update will be posted here in 2-3 hours.

**Comment by sagilson** [comment]
The delay in maintenance of EU regions has been resolved, and the maintenance is now complete. Customer errors past this point will not be the result of the maintenance period and should be handled accordingly.

**Comment by sagilson** [comment]
The maintenance work for 4/4 is scheduled to start at 1:05pm PDT for our US regions. Customers may begin to experience interruptions as described in @danielsollondon's post. An update will be posted on this thread when the maintenance is completed and customers may resume with no interruptions.

**Comment by sagilson** [comment]
The planned maintenance for 4/4 is now complete. Customer errors past this point will not be the result of the maintenance period and should be handled accordingly. 
Thanks for your continued patience as we work to improve the Azure Image Builder experience.

**Comment by danielsollondon** [comment]
Maintenance complete, thank you everyone for your patience.
