### ISSUE TITLE
Image Builder SIG target integration version

### ISSUE THREAD

**Issue by jabbera** [Azure/azvmimagebuilder#25]
Hi,

I'm testing the SIG integration as an output and after running the builder I end up with a seemingly random version number. How can I customize this or at least order it sanely so I can know what versions where historically? Example below where the image version is 0.25088.3355.

```
<gallery>/<imagedef>/0.25088.3355
```

Thanks!
Mike

**Comment by HenryGelderbloem** [comment]
I second this. The version number generated is so random and completely illogical. I suggest that it is possible to define our own version number in the distribution section of the ARM template.

**Comment by jabbera** [comment]
@HenryGelderbloem thanks!
