### ISSUE TITLE
Public access is not permitted on this storage account.

### ISSUE THREAD

**Issue by jortfal** [Azure/azvmimagebuilder#32]
Hello,

I have been trying for two days to generate an image with Image Builder, I have tried all the possible configurations and checked again and again the permissions of the user identity and all the time I get this error:

> <Error>
> <Code>PublicAccessNotPermitted</Code>
> <Message>Public access is not permitted on this storage account. RequestId:0771516a-c01e-0006-7691-4a727d000000 Time:2022-04-07T15:07:21.3330104Z</Message>
> </Error>

This is done by following the tutorial in the [official documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder). However, this does not happen using Azure DevOps. I need it to work with the commands.

Thank you very much.

**Comment by jortfal** [comment]
Hi @danielsollondon,

Do you have any information on this matter?

Thank you.

Best Regards.

**Comment by kof-f** [comment]
Hey @jortfal Azure Image Builder currently does not support storage account firewalls, so if you have a firewall on your storage account then the service will return an error. Do you have a firewall enabled?

**Comment by jortfal** [comment]
I don't currently have access to that storage account and cannot check it. But thank you very much for the information, I will keep it in mind.
