### ISSUE TITLE
Windows 11 24h2 multi session image builder creates linux vm to build image

### ISSUE THREAD

**Issue by Arhughes14** [Azure/azvmimagebuilder#61]
When trying to run image builder to create an image from the Windows 11 Enterprise 24H2 multisession marketplace image, the build fails as image builder is deploying a linux vm on an A1 vm sku. This has been tested creating the template through Terraform and AzApi provider. It has also been tested in the portal and does the same thing. If I build the template using the Windows 11 24H2 Enterprise marketplace image it works fine. Anyone else seeing this issue?

**Comment by ld0614** [comment]
I'm not sure why some SKUs don't tbh as my understanding was that the Linux box gets created every time as it's what hosts the managed packer instance which then connects into the desired VM for customisation

**Comment by Arhughes14** [comment]
Image builder uses container instance now to run Packer. The build VM is what is deployed to configure the customisation settings and this should be the same OS as the source image
